//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hakim.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitReception
    {
        public int VisitReceptionId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public int InsuranceId { get; set; }
        public int UserId { get; set; }
        public int DoctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual User User { get; set; }
    }
}
